{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "yk-update-checker.fullname" . }}
  labels:
    {{- include "yk-update-checker.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get"]
{{- end }}
