# Test values for yk-update-checker
image:
  tag: "0.1.0-alpha"          # defaults to .Chart.AppVersion
scanner:
  config:
    update_type: all          # all | major | minor | patch
    parallel_checks: 5
    git_cache_dir: /tmp/git-cache
    repos:
      - name: my-gitops
        repo: https://github.com/yuriy-kovalchuk/homelab
