{
 "title": "Update Checker",
 "tags": [ "yk-update-checker" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "scope",
    "label": "Scope",
    "query": "All : .+,major : major,minor : minor,patch : patch,unknown : unknown"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Outdated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(update_checker_dependency_outdated_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Major",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(update_checker_dependency_outdated_info{scope=\"major\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(update_checker_dependency_outdated_info{scope=\"minor\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Patch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(update_checker_dependency_outdated_info{scope=\"patch\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(update_checker_dependency_outdated_info{scope=\"unknown\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Scan",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - update_checker_last_scan_time",
     "legendFormat": "Time since last scan"
    }
   ]
  },
  {
   "title": "Outdated Dependencies",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "update_checker_dependency_outdated_info{scope=~\"$scope\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}